services:
  db:
    image: postgres:17
    container_name: postgres-local
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mrq831028
      POSTGRES_USER: zemarques
      POSTGRES_DB: estoque-db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    networks:
      - network-local

volumes:
  postgres_data_local:

networks:
  network-local:
